package com.example.order.mapper;

import com.example.order.model.po.WeightFreightModel;
import com.example.order.model.po.WeightFreightModelExample;
import java.util.List;

public interface WeightFreightModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int insert(WeightFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int insertSelective(WeightFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    List<WeightFreightModel> selectByExample(WeightFreightModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    WeightFreightModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeightFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeightFreightModel record);
}