package com.example.litemall.mapper;

import com.example.litemall.model.po.PieceFreightModel;
import com.example.litemall.model.po.PieceFreightModelExample;
import java.util.List;

public interface PieceFreightModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int insert(PieceFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int insertSelective(PieceFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    List<PieceFreightModel> selectByExample(PieceFreightModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    PieceFreightModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PieceFreightModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PieceFreightModel record);
}